# Generated by Django 3.1 on 2020-08-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('all_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student')),
                ('ucitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ucitel')),
            ],
        ),
    ]
