# Generated by Django 3.1 on 2020-08-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.TextField()),
                ('email', models.FileField(upload_to=None)),
                ('home_address', models.TextField()),
                ('password', models.TextField()),
                ('year_study', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.TextField()),
                ('email', models.FileField(upload_to=None)),
                ('home_address', models.TextField()),
                ('let_ve_skole', models.DecimalField(decimal_places=2, max_digits=75)),
                ('nastup', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
