# Generated by Django 3.1 on 2020-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200810_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='home_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
