# Generated by Django 3.1 on 2020-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200810_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_study',
            field=models.DecimalField(decimal_places=0, max_digits=60),
        ),
    ]
